export enum RiskStateEnum {
  NORMAL = "NORMAL",
  WARNING = "WARNING",
  MARGIN_CALL = "MARGIN_CALL",
  REDUCING = "REDUCING",
  LIQUIDATING = "LIQUIDATING",
  LIQUIDATED = "LIQUIDATED",
  SETTLED = "SETTLED",
  DEFAULT = "DEFAULT",
}
