export enum FreezeActionEnum {
  FREEZE_FREE = "FREEZE_FREE",
  FREEZE_LOCKED = "FREEZE_LOCKED",
  UNFREEZE_FREE = "UNFREEZE_FREE",
  UNFREEZE_LOCKED = "UNFREEZE_LOCKED",
  FREEZE_ENTIRE = "FREEZE_ENTIRE",
  UNFREEZE_ENTIRE = "UNFREEZE_ENTIRE",
}
