/** Withdrawal request lifecycle (spec §5.1). */
export enum P2pWithdrawStateEnum {
  DRAFT = "DRAFT",
  PENDING_MATCHING = "PENDING_MATCHING",
  PARTIALLY_MATCHED = "PARTIALLY_MATCHED",
  ADMIN_SETTLEMENT = "ADMIN_SETTLEMENT",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

/** Deposit intent lifecycle (spec §5.2). */
export enum P2pIntentStateEnum {
  CREATED = "CREATED",
  MATCHING = "MATCHING",
  NO_MATCH = "NO_MATCH",
  RESERVED = "RESERVED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PAYMENT_PROOF_SUBMITTED = "PAYMENT_PROOF_SUBMITTED",
  WAITING_WITHDRAWER_CONFIRMATION = "WAITING_WITHDRAWER_CONFIRMATION",
  REJECTED_BY_WITHDRAWER = "REJECTED_BY_WITHDRAWER",
  WITHDRAWER_RESPONSE_TIMEOUT = "WITHDRAWER_RESPONSE_TIMEOUT",
  ESCALATED_TO_ADMIN = "ESCALATED_TO_ADMIN",
  CONFIRMED = "CONFIRMED",
  REJECTED = "REJECTED",
  REFUNDED = "REFUNDED",
  MORE_INFO_REQUESTED = "MORE_INFO_REQUESTED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum P2pPartStatusEnum {
  OPEN = "OPEN",
  RESERVED = "RESERVED",
  PAID_PENDING = "PAID_PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum P2pMatchStatusEnum {
  RESERVED = "RESERVED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PROOF_SUBMITTED = "PROOF_SUBMITTED",
  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
  REJECTED_BY_WITHDRAWER = "REJECTED_BY_WITHDRAWER",
  RESPONSE_TIMEOUT = "RESPONSE_TIMEOUT",
  ESCALATED = "ESCALATED",
  RESERVATION_EXPIRED = "RESERVATION_EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum P2pSplitPolicyEnum {
  EXACT = "EXACT",
  MAXIMUM = "MAXIMUM",
  RANGE = "RANGE",
}

export enum P2pMatchSourceEnum {
  CUSTOMER = "CUSTOMER",
  ADMIN = "ADMIN",
}

export enum P2pEscalationReasonEnum {
  WITHDRAWER_REJECT = "WITHDRAWER_REJECT",
  WITHDRAWER_NO_RESPONSE = "WITHDRAWER_NO_RESPONSE",
  SETTLEMENT_TIMEOUT = "SETTLEMENT_TIMEOUT",
  RECEIPT_MISMATCH = "RECEIPT_MISMATCH",
  DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT",
  ADMIN_ACCOUNT_UNAVAILABLE = "ADMIN_ACCOUNT_UNAVAILABLE",
}

export enum P2pEscalationStatusEnum {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  RESOLVED = "RESOLVED",
  VOID = "VOID",
}

/** The six decisions an admin may record (spec §7.2). */
export enum P2pResolutionTypeEnum {
  CONFIRM_PAYMENT = "CONFIRM_PAYMENT",
  REJECT_PAYMENT = "REJECT_PAYMENT",
  REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE",
  SETTLE_FROM_ADMIN = "SETTLE_FROM_ADMIN",
  REOPEN_MATCHING = "REOPEN_MATCHING",
  CANCEL_REQUEST = "CANCEL_REQUEST",
}

export enum P2pAuditActorEnum {
  USER = "USER",
  ADMIN = "ADMIN",
  SYSTEM = "SYSTEM",
}

export enum P2pSourcePriorityEnum {
  CUSTOMER_FIRST = "CUSTOMER_FIRST",
  ADMIN_FIRST = "ADMIN_FIRST",
}
