export enum FeatureKeyEnum {
  TRADING_DAILY_LIMIT = "TRADING_DAILY_LIMIT",
  TRADING_MAX_ORDER_VALUE = "TRADING_MAX_ORDER_VALUE",
  TRADING_MAX_OPEN_ORDERS = "TRADING_MAX_OPEN_ORDERS",
  WALLET_WITHDRAWAL_DAILY_LIMIT = "WALLET_WITHDRAWAL_DAILY_LIMIT",
  WALLET_WITHDRAWAL_PER_TX_LIMIT = "WALLET_WITHDRAWAL_PER_TX_LIMIT",
  CREDIT_MAX_AMOUNT = "CREDIT_MAX_AMOUNT",
  CREDIT_MAX_DURATION_DAYS = "CREDIT_MAX_DURATION_DAYS",
  TELEGRAM_BOT_ENABLED = "TELEGRAM_BOT_ENABLED",
  API_ACCESS_ENABLED = "API_ACCESS_ENABLED",
  ELITE_TRADE_ENABLED = "ELITE_TRADE_ENABLED",
  PRIORITY_SUPPORT = "PRIORITY_SUPPORT",
  MAX_MARKET_TYPES = "MAX_MARKET_TYPES",
}
