export enum TransactionTypeEnum {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  BUY = "BUY",
  SELL = "SELL",
  ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT",
  FEE = "FEE",
  REFERRAL = "REFERRAL",
  ORDER = "ORDER",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_REJECTED = "ORDER_REJECTED",
}
